export const menuItems = [
  { label: "Trang chủ", href: "/" },
  {
    label: "Sản phẩm",
    href: "/san-pham",
    children: [
      { label: "Tính năng nổi bật", href: "/san-pham/tinh-nang-noi-bat" },
      { label: "Tổng quan phần mềm", href: "/san-pham/tong-quan" },
      { label: "Quản lý chi phí - Giá thành", href: "/san-pham/quan-ly-chi-phi-gia-thanh" },
      { label: "Quản lý TSCĐ - CCDC", href: "/san-pham/quan-ly-tscd-ccdc" },
      { label: "Quản lý hàng tồn kho", href: "/san-pham/quan-ly-hang-ton-kho" },
      { label: "Quản lý bán hàng", href: "/san-pham/ban-hang" },
      { label: "Quản lý mua hàng", href: "/san-pham/mua-hang" },
      { label: "Kế toán tài chính", href: "/san-pham/ke-toan-tai-chinh" },
      { label: "Nâng cấp Dashboard BI", href: "/san-pham/nang-cap-dashboard-bi" },
      { label: "Kết nối trạm cân", href: "/san-pham/ket-noi-tram-can" },
      { label: "Quản lý tồn kho bằng Barcode", href: "/san-pham/quan-ly-ton-kho-bang-barcode" },
      { label: "Quan hệ khách hàng - CRM", href: "/san-pham/quan-he-khach-hang-crm" },
      { label: "Quản lý nhân sự - Tính lương", href: "/san-pham/quan-ly-nhan-su-tinh-luong" },
      { label: "ROSY WEB", href: "/san-pham/rosy-web" },
      { label: "Quản trị sản xuất", href: "/san-pham/quan-tri-san-xuat" },
    ],
  },
  {
    label: "Dịch vụ",
    href: "/dich-vu",
    children: [
      { label: "Giới thiệu chung", href: "/dich-vu/gioi-thieu" },
      { label: "Chăm sóc khách hàng", href: "/dich-vu/cham-soc-khach-hang" },
      { label: "Tùy chỉnh, cài đặt phần mềm", href: "/dich-vu/tuy-chinh-cai-dat-phan-mem" },
      { label: "Đào tạo, Hỗ trợ sử dụng", href: "/dich-vu/dao-tao-ho-tro-su-dung" },
      { label: "Bảo hành, Bảo trì phần mềm", href: "/dich-vu/bao-hanh-bao-tri-phan-mem" },
      { label: "Tư vấn giải pháp", href: "/dich-vu/tu-van-giai-phap" },
    ],
  },
  {
    label: "Giải pháp",
    href: "/giai-phap",
    children: [
      { label: "Giải pháp hóa đơn điện tử đầu vào", href: "/giai-phap/hoa-don-dien-tu-dau-vao" },
      { label: "Rosy ứng dụng di động trong sản xuất", href: "/giai-phap/ung-dung-di-dong-trong-san-xuat" },
      { label: "Giải pháp hóa đơn điện tử Rs-Invoice", href: "/giai-phap/hoa-don-dien-tu-rs-invoice" },
      { label: "Giải pháp ngành Bao Bì - In Ấn", href: "/giai-phap/nganh-bao-bi-in-an" },
      { label: "Giải pháp Sợi - Dệt - Nhuộm - May", href: "/giai-phap/soi-det-nhuom-may" },
      { label: "Giải pháp Kết Nối Trạm Cân", href: "/giai-phap/ket-noi-tram-can" },
      { label: "Giải pháp Chuyên Ngành Nội Thất", href: "/giai-phap/chuyen-nganh-noi-that" },
      { label: "Giải pháp Tồn Kho Barcode", href: "/giai-phap/ton-kho-barcode" },
      { label: "Giải pháp Giao Nhận, Vận Chuyển", href: "/giai-phap/giao-nhan-van-chuyen" },
      { label: "Giải pháp Bảo Trì Máy Móc Thiết Bị", href: "/giai-phap/bao-tri-may-moc-thiet-bi" },
    ],
  },
  {
    label: "Tin tức",
    href: "/tin-tuc",
    children: [
      { label: "Tin Dự Án", href: "/tin-tuc/tin-du-an" },
      { label: "Tin Công nghệ", href: "/tin-tuc/tin-cong-nghe" },
      { label: "Tin Tài chính", href: "/tin-tuc/tin-tai-chinh" },
      { label: "Tin Nội bộ", href: "/tin-tuc/tin-noi-bo" },
    ],
  },
  { label: "Đối tác", href: "/doi-tac" },
  { label: "Tuyển dụng", href: "/tuyen-dung" },
  { label: "Về chúng tôi", href: "/ve-chung-toi" },
  { label: "Liên hệ", href: "/lien-he" },
];