# Cổng chạy Backend
server.port=8080
# Kết nối tới MongoDB Docker (Dùng tài khoản admin đã tạo ở file docker-compose)
spring.mongodb.uri=mongodb://admin:password123@localhost:27017/rosy_erp?authSource=admin

# Hiển thị log query để dễ debug
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
spring.application.name=backend
